name: 'Setup TinyGo environment'
description: 'Setup a TinyGo environment and add it to the PATH'
inputs:
  go-version:
    description: 'The Go version'
    required: false
    default: 1.25.5
  tinygo-version:
    description: 'The TinyGo version'
    required: false
    default: 0.41.1
runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ inputs.go-version }}
    - name: Cache TinyGo
      id: cache-tinygo
      uses: actions/cache@v6
      with:
        path: ./tinygo_${{ inputs.tinygo-version }}_amd64.deb 
        key: tinygo_${{ inputs.tinygo-version }}_amd64.deb
    - name: Download TinyGo
      if: steps.cache-tinygo.outputs.cache-hit != 'true'
      shell: bash
      run: wget -q https://github.com/tinygo-org/tinygo/releases/download/v${{ inputs.tinygo-version }}/tinygo_${{ inputs.tinygo-version }}_amd64.deb
    - name: Install TinyGo
      shell: bash
      run: sudo dpkg -i tinygo_${{ inputs.tinygo-version }}_amd64.deb
    - name: Export TinyGo path
      shell: bash
      run: echo "/usr/local/bin" >> $GITHUB_PATH
    - name: Print TinyGo version
      shell: bash
      run: tinygo version