name: CI
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.40.1
      options: --user 1001
    outputs:
      examples: ${{ steps.examples.outputs.matrix }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Install dependencies
        run: npm ci
      - name: Build library and plugin
        run: npm run build
      - name: List examples
        id: examples
        run: |
          examples=$(ls -d ./examples/*/ | xargs -n1 basename | awk -v ORS=',' '{print "\""$0"\""}' | sed 's/,$//')
          echo "matrix=[${examples}]" >> $GITHUB_OUTPUT
      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/
          retention-days: 1
  build-examples:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.40.1
      options: --user 1001
    strategy:
      matrix:
        example: ${{ fromJson(needs.build.outputs.examples) }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - name: Install dependencies
        run: npm --prefix "./examples/${{ matrix.example }}" ci
      - name: Build example
        run: npm --prefix "./examples/${{ matrix.example }}" run build -- --base /two/${{ matrix.example }}/
      - name: Upload example
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.example }}
          path: examples/${{ matrix.example }}/dist/
          retention-days: 1
  deploy:
    needs: build-examples
    runs-on: ubuntu-latest
    container:
      image: tinygo/tinygo:0.40.1
      options: --user 1001
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v6
      - name: Create directory
        run: mkdir two
      - name: Download examples
        uses: actions/download-artifact@v4
        with:
          path: two/
          pattern: '!dist'
      - name: Generate index.html
        run: |
          index_html=$(go run index/index.go two/)
          echo "$index_html" > two/index.html
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./two/
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com